### ISSUE TITLE
Unable to Access Auto-email Admin URL

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#12]
Hi Zent,
I've merged your latest pull-request https://github.com/usbong/UsbongStore/commit/3cd256c968eb878cf26b9738c974d5deff606e85, and have downloaded it to my Ubuntu in VirtualBox.

May I ask how to reconfigure the default route?
According to your email, it can be accessed here:
https://store.usbong.ph/index.php/auto-email

At present, I am using the following URL to access my local copy of the Usbong Store:
http://localhost/usbong_store

This is the same address specified in `application/config/config.php`.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Kindly try the ff:
http://localhost/usbong_store/auto-email

http://localhost/usbong_store/index.php/auto-email

Thanks lots!

On Oct 15, 2017 8:11 AM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
I've merged your latest pull-request 3cd256c
<https://github.com/usbong/UsbongStore/commit/3cd256c968eb878cf26b9738c974d5deff606e85>,
and have downloaded it to my Ubuntu in VirtualBox.

May I ask how to reconfigure the default route?
According to your email, it can be accessed here:
https://store.usbong.ph/index.php/auto-email

At present, I am using the following URL to access my local copy of the
Usbong Store:
http://localhost/usbong_store

This is the same address specified in application/config/config.php.

Thank you.

Peace,
Mike

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/12>, or mute the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the email.

For some reason, when I enter the following as my URL, I end up with the Apache2 Ubuntu Default Page.
http://localhost/usbong_store

I tested creating a new folder and an html file like this:
`/var/www/html/test/index.html`

When I use the following URL, I am able to access it.
http://localhost/test/

My hunch is that I must have put in a wrong configuration or have not restarted a service.

I have, however, checked my configuration and restarted the Apache2 service.

Would you be able to offer suggestions on how I may be able to resolve this issue?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Afternoon Mike,

I ll send you my configuration this evening when i get access to my laptop.

Catch up with u soon. 😊

**Comment by masarapmabuhay** [comment]
Thank you, Zent!

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike,

Below is rough guide for my local env.

Your env will likely be structured very similarly.

Please try the instructions below.

Evening!

<----------Details Follow---------->

====================
ACTIVATE LOCAL ENV
====================

(1) Place UsbongStore in /var/www/html

(2) Create apache conf for usbong store

    (a) Location: /etc/apache2/sites-available/

    (b) Create File store.usbong.ph.conf

    (c) Place the ff inside:

        <VirtualHost *:80>
            ServerAdmin zentlim@gmail.com
            ServerName usbong.ph
            ServerAlias store.usbong.ph
            DocumentRoot /var/www/html/UsbongStore/usbong_store

            <Directory "/var/www/html/UsbongStore/usbong_store">
            # allow .htaccess to override default options
            AllowOverride All
            </Directory>

            # uncomment the line below to debug mod_rewrite
            LogLevel alert rewrite:trace3
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
        </VirtualHost>

        <VirtualHost *:443>
            ServerAdmin zentlim@gmail.com
            ServerName usbong.ph
            ServerAlias store.usbong.ph
            DocumentRoot /var/www/html/UsbongStore/usbong_store

            SSLEngine On
            SSLCertificateFile /home/zent/ssl/crt/vhost1.crt
            SSLCertificateKeyFile /home/zent/ssl/key/vhost1.key

            <Directory /var/www/html/my_start_ups/web>
                # allow .htaccess to override default options
                AllowOverride All
            </Directory>

            <Location />
                SSLRequireSSL On
                SSLVerifyClient optional
                SSLVerifyDepth 1
                SSLOptions +StdEnvVars +StrictRequire
            </Location>

            # uncomment the line below to debug mod_rewrite
            LogLevel alert rewrite:trace3
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
        </VirtualHost>



*     (d) segment 80 is for http while segment 443 is for https*


*          Please include segment 443 first and let's see if it will work
even if you don't have open ssl in your local*

*          If it returns error, please try to remove segment 443*

(3) Clear browser cache

(4) Update apache hosts file

   (a) Location: /etc/hosts

   (b) Add the ff:

       127.0.1.4 store.usbong.ph

(5) Activate Virtual Host for usbong store using command line:

    sudo a2ensite store.usbong.ph.conf

(6) Restart apache using command line:

    sudo service apache2 reload

    sudo service apache2 restart

(7) Acessing the url below shoould now let ur local machine to the local
server instead of live server

    https://store.usbong.ph

====================
DISABLE LOCAL ENV
====================

(1) Clear browser cache

(2) Update apache hosts file

   (a) Location: /etc/hosts

   (b) Coment out the ff with a leading '#':

       # 127.0.1.4 store.usbong.ph

(3) Disable Virtual Host for usbong store using command line:

    sudo a2dissite store.usbong.ph.conf

(4) Restart apache using command line:

    sudo service apache2 reload

    sudo service apache2 restart

(5) Acessing the url below shoould now let ur local machine access live
server

    https://store.usbong.ph

**Comment by zent-lim** [comment]
Hi Mike,

Alternative easy version.

Current Location of usbong_sore:
/var/www/html/UsbongStore/usbong_store

New Location of usbong_store:
/var/www/html/usbong_store

You'll then be able to access local env using:
https://localhost/usbong_store

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the advice.

It seems that clearing my browser's cache produced a change.

Now, when I enter the following URL I get a blank page:
http://localhost/usbong_store

It may be due to my `.htaccess`.

Can you show me the contents of your `.htaccess` if you're running Usbong Store and Auto-email locally?

I understand that it should be located as a hidden file here:
/var/www/html/.htaccess

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

=================
YOUR QUESTION
=================

(1) .htaccess should be located in web root. Depending on your
configuration, it should be either in:

(a) /var/www/html/UsbongStore/usbong_store/.htaccess

(b) /var/www/html/usbong_store/.htaccess

(2) My .htaccess is same as yout git .htaccess.

(3) Below is content:

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]

(4) Mine is in:
/var/www/html/UsbongStore/usbong_store

=================
MISC
=================

(1) To access local usbong_store using the url below...
http://localhost/usbong_store

(2) Your dir structure should be:
/var/www/html/usbong_store

(3) The original structure is:
/var/www/html/UsbongStore/usbong_store

Please let me know if more complications occur. :)

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, I also have my .htaccess here:
/var/www/html/usbong_store/.htaccess

Unfortunately, even with the same content as yours, I still get a blank page when I go to this URL:
http://localhost/usbong_store

I am now installing Ubuntu in a new instance in VirtualBox, and will redo the steps.

I was able to already access the home page of Usbong Store, and was only getting an error when I click a link in the page, saying something to the effect of:

> Cannot find /usbong_store/account/login/


One of the changes that I made to hopefully fix the issue must have caused my CodeIgniter configuration to break, such that the blank screen now appears.

Actually, even accessing phpmyadmin also now produces errors.
http://localhost/phpmyadmin

So the error may be related to accessing the DB.

In the meantime, I will let you know if things improve with the new Ubuntu installation.

Thank you for your kindness.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Please read on.

On Tue, Oct 17, 2017 at 9:06 AM, Masarap Mabuhay <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> Yes, I also have my .htaccess here:
> /var/www/html/usbong_store/.htaccess
>
Ok.

> Unfortunately, even with the same content as yours, I still get a blank
> page when I go to this URL:
> http://localhost/usbong_store
>
> I am now installing Ubuntu in a new instance in VirtualBox, and will redo
> the steps.
>
> I was able to already access the home page of Usbong Store, and was only
> getting an error when I click a link in the page, saying something to the
> effect of:
>
> Cannot find /usbong_store/account/login/
>
>
Below are similar issues I encountered while setting up my local env:

(1) If it's a white page with orange highlights, the update below in my
config solved it in my local:
NEW:
$config['index_page'] = 'index.php';//'index.php';

ORIG:
$config['index_page'] = '';//'index.php';

NOTE:
This translates to links being written as follows:
http://localhost/usbong_store/index.php/account/login

(2) please check if controller filenames are capitalized in your
environment. If not, please capitalize them. But I think you already
resolved this in the past.


> One of the changes that I made to hopefully fix the issue must have caused
> my CodeIgniter configuration to break, such that the blank screen now
> appears.
>
Ok.

> Actually, even accessing phpmyadmin also now produces errors.
> http://localhost/phpmyadmin
>
> So the error may be related to accessing the DB.
>
Try to run the ff in command line so you don't debug blindly:

locate error | grep apache

This will show you a bunch of error logs and maybe one of those logs can
point out what's wrong.

In the meantime, I will let you know if things improve with the new Ubuntu
> installation.
>
No prob! Please buzz back if there's something I can do.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Good news! I was able to successfully install the Usbong Store on my Ubuntu in a new instance of VirtualBox.

I've written down the steps that I took:
https://github.com/usbong/UsbongStore/wiki

I shall now be testing the auto-email component:
https://store.usbong.ph/index.php/auto-email

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Cool! 😀

I ll stand by for ur feedbacks. Have a good evening ahead! 😁

**Comment by masarapmabuhay** [comment]
Thank you!

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
I've transferred all the auto-email files from repo to our prod.
I've also imported the auto-email MySQL files to our prod DB.

However, when I access the following URL, I get a `404 Page Not Found` error.
https://store.usbong.ph/auto-email

1) I've also already logged in.
2) All the controller file names are capitalized.
3) Updating my config file: `$config['index_page'] = 'index.php';` did not resolve the issue.

What could be the probable cause?
 
Thank you for your patience.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike,

========
ANSWER
========

(1) The most probable cause is:
config/route.php

(2) Please check if the lines below are missing:

// routing for auto-email controller
// routing rules are needed cause auto-email controllers are located in
controllers/auto-email instead of controllers/
$route['auto-email']                               =
'auto-email/administer/index';
$route['auto-email/administer/(:num)']             =
'auto-email/administer/index/$1';
$route['auto-email/queue/(:num)/(:num)']           =
'auto-email/administer/queue/$1/$2';
$route['auto-email/create/template/(:num)']        =
'auto-email/administer/create/template/$1';
$route['auto-email/create/data']                   =
'auto-email/administer/create/data';
$route['auto-email/create/products/(:num)/(:any)'] =
'auto-email/administer/create/products/$1/$2';
$route['auto-email/create/products/(:num)']        =
'auto-email/administer/create/products/$1';
$route['auto-email/create/save']                   =
'auto-email/administer/create/save';

(3) Reference:
Subject: Auto Email Milestone 4: Admin UI V01
Date: 10/14/17
Section: Update > (1) Code > Notes > (i)
Comment: I updated common file config/route.php to configure routes based
on your prescribed controller directory structure controllers/auto-email.

========
REQUEST
========

Please inform me if this does not solve the problem.

P.S.
It's best to also have git in live server so you just pull code from live
server to git. It saves a lot of time.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

When I enter the following URL, I get `Message: syntax error, unexpected '　' (T_STRING)`
https://store.usbong.ph/auto-email

This is in Line Number 58: `$route['auto-email']　=　'auto-email/administer/index';`

What could be the problem?

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) It's the first time I saw that error message.

(2) Since you placed "index.php" in $config['index_page']...

(3) Could you try this url:

    https://store.usbong.ph/index.php/auto-email

    Instead of this url:


    https://store.usbong.ph/auto-email

Fingers crossed. Maybe, we'll get lucky. Please inform me of the next
problem. :)

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Good news! We've resolved the issue!

1) Maintained `$config['index_page'] = '';`

2) Added the routing rules you indicated in your message, but using the text in our [GitHub repo](https://github.com/usbong/UsbongStore/blob/master/usbong_store/application/config/routes.php ), instead of the one in your comment.

3)  Used: `https://store.usbong.ph/auto-email`

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Awesome!

Have a good day ahead!

Feel free to buzz for further concerns. 😀

**Comment by masarapmabuhay** [comment]
Thank you.

Peace,
Mike
