### ISSUE TITLE
Auto-email: Cannot add or update a child row: a foreign key constraint fails 

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#13]
Hi Zent,
I was almost done with creating my first auto-email using the auto-email interface, when after clicking the "Create New Batch" button, I encountered the following error:
 
```
A Database Error Occurred

Error Number: 1452

Cannot add or update a child row: a foreign key constraint fails (`usbong_store`.`auto_email_schedule`, CONSTRAINT `auto_email_schedule_fk_end_customer_id` FOREIGN KEY (`end_customer_id`) REFERENCES `customer` (`customer_id`) ON UPDATE CASCADE)

INSERT INTO `auto_email_schedule` (`auto_email_id`, `start_customer_id`, `end_customer_id`, `start_datetime`, `status`) VALUES ('2', '1', '30', '2017-10-18 18:26:10', 'QUEUED')

Filename: models/auto-email/Auto_Email_Schedule_Model.php

Line Number: 274

```

Could it be that the code on GitHub is not the updated one?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

===================
ROUGH ANALYSIS
===================

(1) The ids chosen does not exist.

To maintain database integrity, writing customer_id to auto-email related
database tables first checks if the actual customer_id exists.

(2) By the time you reach the page with "Create New Batch", a new email has
already been created.

So when you visit the url below, a new email entry should be available in
the listed entries:
XXX/auto-email

===================
MAYBE NOT A PROBLEM
===================

The code should have failed safely as shown in the image below:

(I also attached the image in case it doesn't display on your end.)


​
===================
WHY THE CODE DID NOT FAIL SAFELY
===================

(1) The code most likely did not fail safely because of the line of code
here:

      (a) File: UsbongStore/usbong_store/application/config/database.php

      (b) Field: 'db_debug' => (ENVIRONMENT !== 'production'),

      (c) Note: If you're running in local, by definition this is set to
TRUE

       When this field is set to TRUE, Codeigniter will throw an error
immediately to show the DB error to the author for faster debugging.

*This makes the code skip some of the fail safes that I wrote.*

(2) Please set the above field to FALSE to mimic your production
environment.

(3) Please check if code fails safely with this setting.

On the other hand, if the problem persists, please inform me. I will
investigate further.

Thank you.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, you are correct. 

I can see my auto-email subject as a row in the auto-email table.

The error disappeared after I did the following:

In `.../usbong_store/application/config/database.php`, I changed `!==` to `==`, 

such that it is now:

`'db_debug' => (ENVIRONMENT == 'production'),
`

This issue is now closed.

Thank you. 

Peace,
Mike

**Comment by zent-lim** [comment]
Ok Mike!

P.S.
Please don't use this in your production server:

'db_debug' => (ENVIRONMENT == 'production'),

Local env, it's ok to use the above setting.

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the advice.

Yes, I am using an Ubuntu instance in VirtualBox, which is in my local
environment.

Peace,
Mike
--
Usbong: Uplifting Human Lives
*www.usbong.ph <http://www.usbong.ph/>*
--
Michael B. Syson
