### ISSUE TITLE
Auto-email: After clicking "Creating New Batch", email is not sent to customers

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#15]
Hi Zent,
I've successfully set my auto-email content using the auto-email interface, while making sure that the customer ID is valid.

However, after clicking the "Creating New Batch" button, the email is not sent to the customers.

Auto-email did not also report any errors.

The batch details were also added as a row in the auto-email queue.

What could be the probable cause?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) Milestone 4 (Admin UI) is designed to prepare data for Milestone 2
(Cron Script).

(2) The two should work together to send out emails. Now that you have set
data using the admin UI, the cron script has something to kick.

(3) Please kick the cron script to send out the email.

(4) *Or better yet*, schedule the cron scipt to kick every few minutes. In
my live server for mystartups.ph, I use 15 minute intervals.

# syntax may depend on your server environment
# this one is for cent os
00,15,30,45 * * * * /home/mystartups/public_html/my_start_ups/./yii
newsletter-personal-broadcast/run >/dev/null 2>&1

# this one is for ubuntu
00,15,30,45 * * * * /var/www/html/my_start_ups/./yii
newsletter-personal-broadcast/run

The script is smart enough to identify if it has a task or not. So if it is
kicked with nothing in queue, it will still run safely.

Similarly, if it encounters an error, it will pause a queue and you will
see the error in your admin UI.

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
I was able to send an auto-email using:
`php index.php auto-email/autoemail run
`

I have emailed you the output email.

Observations:
1) The images do not display properly.
2) The subject header is also incorrect.

What could be the probable cause?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike!

=====================
Regarding Wrong Subject
=====================

*I think the following happened:*

(1) Prior to your kick, you had two emails with one queue each.
      (a) First Email: Test Email from My Default SQL
      (b) Second Email: The Email you created

(2) When you kicked once, (1)(a) above was kicked. If I remember right,
only one email will receive this (customer 1).

*Checking What Happened:*

(1) Please check your current emails and queue using the url below:
..../auto-email

(2) And if you have logging turned on, you'll be able to see what happened
on your last kick in:
UsbongStore/usbong_store/application/logs/log-2017-10-19.php

*Solving the Current Issue:*

I think if you kick again, the email you created will be sent next since
it's the next item in queue.

=====================
Regarding No Images
=====================

Most likely, it is the issue we encountered before.

Gmail can only communicate with your live server.

Since you are kicking using local server, please mimic url creation like
live server by doing the ff:

File: UsbongStore/usbong_store/application/config/config.php

Field: $config['base_url'] = 'https://store.usbong.ph/';

Please let me know if this solves your issues.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, you are correct.
After I sent the second email, auto-email used the correct subject header.

Regarding the images, is there a way to use the images from prod, while using the local server?

I prefer to use my local server for auto-emails.

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Ok regarding wrong subject. I will abort trying to recreate the test case.

Regarding images:

Please mimic url creation like live server by doing the ff:

File: UsbongStore/usbong_store/application/config/config.php

Field: $config['base_url'] = 'https://store.usbong.ph/';

P.S.
I think I encountered a bug from your code clean up. Investigating now.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, I have tested configuring my Ubuntu's config.php.
`$config['base_url'] = 'https://store.usbong.ph/';`

However, what happens is that I'll have to access auto-email in prod.

I hope we can figure out a way to resolve this.

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Sorry I don't understand the problem.

To my understanding, for test purposes, you want the email recipient's
browser to open the email and see the images on live server.

Did I understand correctly?

If yes, setting the field below does it:
File: UsbongStore/usbong_store/application/config/config.php
Field: $config['base_url'] = 'https://store.usbong.ph/';

Please elaborate.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I would like to use my Ubuntu in my local VirtualBox to send the auto-email.
However, the auto-email sent from local doesn't properly display images, because they're stored in prod, i.e. https://store.usbong.ph.

Is there a way for me to use my local environment to send auto-emails with the images properly displayed?

Or do I really have to use auto-email in prod?

Please never hesitate to let me know if I'm not being clear.

Thank you for your patience.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Now i understand.

For gmail email client, it is not possible.

The short version is, gmail modifies the image url we send out.

The image url we send out is not the same as the image url gmail uses to
show the recipient.

Gmail most likely fetches from the image url we set, saves the image in it
s server, and uses it s own image url to render to the recipient.

To check, pls go back to one of our old emails and click browser's "inspect
element" on the image src attribute. You will notice that the source url
looks encrypted.

Since gmail has no access to ur local server, it can not fetch an image
file from it, causing it to fall back to some string text instead of an
image.

Pls inform me if i need to elaborate further.

Thanks!

**Comment by zent-lim** [comment]
Hi Mike,

(1) Shown is src attribute of image in an email opened in gmail client. As
you can see, gmail updates it to fetch from some google domain:

https://ci5.googleusercontent.com/proxy/Xrlh7siliC_xAV06b155TjEF0FPw_b_e9-mpmM83xdicFvho_2_Uwi4I7vcuhHxRBPHjqiccFPRL3-qmrpREelcdLWjOteUK3TGJKc1pufKUT6vkkn8li-LhKDHn26LT-KmltgHOB873yRoweWA4GunYj1YZk2SC5CmiFK3vmWQHdVitmDEYvAvoeH-nYPVM-P2gz3TqDR8sCIs9ZymAomhnZqDLqGca3cqf2GXLIqCWJ4LT9oNqJg=s0-d-e1-ft#https://store.usbong.ph/assets/images/textbooks/BJT%20Business%20Japanese%20Proficiency%20Test%20Listening%20and%20Reading%20Comprehension%20(with%202%20CDs).jpg

(2) Please see attached file for more details.

(3) In your live server, base_url is set to "
http://localhost:8080/usbong_store/". There is something in your live
server that equates that to https://store.usbong.ph. Most likely a file
called /etc/hosts.

(4) After you finish testing the auto-email feature in your local
environment, we should also test it in your live server to see if it can
run with base_url set to "http://localhost:8080/usbong_store/".

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK! I'll have to put auto-email to prod then.

Thank you.

Peace,
Mike
p.s.  it seems that the attached file you mentioned did not get included.

**Comment by zent-lim** [comment]
Hi Mike,

I forwarded the file to ur personal email. Afternoon! ☺

**Comment by masarapmabuhay** [comment]
Thank you, Zent!

I received your email with the file attachment.

Peace,
Mike

--
Usbong: Uplifting Human Lives
*www.usbong.ph <http://www.usbong.ph/>*
--
Michael B. Syson
