### ISSUE TITLE
Auto-email: Is there a way to modify the sender name?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#17]
Hi Zent,
Is there a way to modify the sender name?

It seems that it's set (as default) to "Mike from Usbong".

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

=========
ANSWER
=========

Kindly update database > usbong_store > auto_email_setting > row 8
(sender_alias) > column value to the desired string.

=========
ACTION
=========

I updated wiki page with the info above:

https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature

=========
QUESTION
=========

What default value would you like?

I will update sql.

The name "Mike from Usbong" was chosen because from a marketing
perspective, using a real person's name gets higher open rate.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! I can see the row (sender_alias) you are referring to.

Let's use "Usbong.ph" for the default sender_alias.

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I uploaded v5 mwb and sql to:
https://github.com/usbong/UsbongStore/tree/master/auto-email

Evening!

**Comment by masarapmabuhay** [comment]
Thank you, Zent!

Peace,
Mike
--
Usbong: Uplifting Human Lives
*www.usbong.ph <http://www.usbong.ph/>*
--
Michael B. Syson
