### ISSUE TITLE
DB Schema `product column`.`product_id` and `customer`.`customer_id` is recommended to be Unsigned INT instead of Signed INT

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#2]
Currently the following primary keys are set to signed INT.

(1) `product column`.`product_id`

(2) `customer`.`customer_id`

The following was used for reference:
https://github.com/usbong/UsbongStoreApp/blob/master/db/usbong_store20170923.sql

Since it's a primary key, I don't see a use case where it will be used as a negative number.

Setting it to signed INT looses one binary digit, loosing some values in the upper limit.

RECOMMENDATION:

Changing it now may damage backward compatibility.

I think it's best to maintain them as is.

AFFECTED CONCERNS:

New tables in auto email feature which requires foreign keys attached to the said ids will also used SIGNED INT instead of UNSIGNED INT.

**Comment by zent-lim** [comment]
In usbong_store_auto_email_v01.sql, the following affected attributes also use SIGNED INT instead of UNSIGNED INT:

(1) `auto_email_schedule`.`start_customer_id`
(2) `auto_email_schedule`.`end_customer_id`
(3) `auto_email_sent`.`customer_id`
(4) `auto_email_product`.`product_id`

**Comment by masarapmabuhay** [comment]
Hi Zent, 
Thank you for bringing this up.

We were using the default attribute for the primary keys you indicated, i.e. customer_id and product_id. It turned out that the default is **SIGNED** INT.

In any case, we are actually using negative values for the customer_id. For example, if a customer uses search, the searched item is stored in the DB.

If the customer did not log in, the customer_id would be a negative value, i.e. -1.

I hope I was able to satisfactorily resolve this issue.

Thank you for providing feedback.

Peace.

**Comment by zent-lim** [comment]
Hi Mike,

Thank you for explaining that negative values are used.

In which case, this is not a bug nor a future  enhacement.

Thank you for closing.

**Comment by masarapmabuhay** [comment]
OK! Thank you. Peace.
