### ISSUE TITLE
Auto-email: After creating a new batch, do not delete it in the queue

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#21]
Hi Zent,
After I sent a new batch via auto-email, I noticed that auto-email deletes it from the queue.

Is there a way to store it as some sort of part of a queue history for reuse?

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

========
ANSWER
========

(1) The database records a "compressed version" of what was sent out in
table `auto_email_schedule`. It shows you lower and upper bound of the
customers targeted.

(2) In your UI, you can see this in the url below:

https://store.usbong.ph/index.php/auto-email/queue/[auto_email_id]/[page]

(3) Please see attached file Queue.png for screen shot.

========
MISC
========

(1) The table `auto_email_sent` on the other hand, deletes records when a
batch finishes.

(2) This delete was done by design.

(3) This table is meant to be used as scratch pad mainly for error
recovery. Meaning, if an email fails to send, the control logic will be
able to point where it should continue on the next kick,

(4) Delete is done per batch complete because items are recorded one by
one. This table can get big fast. If it gets big, the script might function
very slowly in the future.

(5) Should you wish to not delete, below are the lines of code to be
commented out.

File:
UsbongStore/usbong_store/application/controllers/auto-email/Autoemail.php

Code:

            // set queue to DONE
            log_message($this->log_level, $this->log_marker.'QUEUE SET to
DONE.');

$this->Auto_Email_Schedule_Model->setStatus($this->ctrl['auto_email_schedule']->auto_email_schedule_id,
'DONE');

$this->Auto_Email_Sent_Model->deleteRowsByAutoEmailScheduleId($this->ctrl['auto_email_schedule']->auto_email_schedule_id);

Comment Out:

$this->Auto_Email_Sent_Model->deleteRowsByAutoEmailScheduleId($this->ctrl['auto_email_schedule']->auto_email_schedule_id);

Note:

If line of code is removed, I am unsure of complications. But a quick look
shows it should be ok other than the performance issue when the table gets
big.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. In that case, I'll have to comment out the lines of code you specified if I want to reuse a batch.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike!

Could you explain what you mean by "reuse"?

I dont think deleting the line of code will allow you to "reuse" a batch.

Thank you.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

What I meant by "reuse" was to be able to "Create a New Batch" using the auto-email data.

However, upon verifying this again, it seems that I can in fact already do so, by going to the following URL and choosing ACTION.
https://store.usbong.ph/auto-email/

Please correct me if my understanding is wrong.

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Thank you for explaining.

Yes.

(1) There is no need to modify source code.

(2) Simply click the "Menu Icon" under the Action segment as you have
stated here.

Have a good day ahead! :)

**Comment by masarapmabuhay** [comment]
Thank you, Zent!

Peace,
Mike
