### ISSUE TITLE
Auto-email: Created Batch is not emailed

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#24]
Hi Zent,
I am able to successfully create a new batch, but it is not emailed by auto-email even if the settings, e.g. start and end customer ids, target kick, are correct and valid.

I may have missed configuring something in prod.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

=============
INFO
=============

The auto email front end UI sets up data for the kick script.

The script needs to be kicked for emails to be sent.

=============
DEBUG STEPS
=============

Kindly do the ff debug steps:

CHECK IF SOMETHING IS IN QUEUE

(1) Open your auto-email dashboard at either of the url below (depending on
your server setup):
https://store.usbong.ph/auto-email

https://store.usbong.ph/index.php/auto-email

(2) Note Column "Batches Sent": X/Y

     If X < Y, most likely something needs to be sent out.

     The other factor is the target kick time you have set.

     If the target kick time is already in the past, then you have
something to kick in the queue.

     If the target kick time is in the future, then you have nothing to
kick in the queue.

ACTIVATE LOGGING TEMPORARILY

(1) Open File application/config/config.php in live server

(2) Set $config['log_threshold'] to 3

KICK THE SCRIPT

If you have set up something to be kicked...

(1) connect to your live server using ssh.

(2) go to /xxx/UsbongStore/usbong_store

(3) Run:

php index.php auto-email/autoemail run


VERIFY WHAT HAPPENED USING LOG FILE

(1) Go to UsbongStore/usbong_store/application/logs/ and look for the
latest log file.

(2) Read what happened by searching for "AutoEmail"

VERIFY WHAT HAPPENED USING FRONT END DASHBOARD

(1) Open your auto-email dashboard at either of the url below (depending on
your server setup):
https://store.usbong.ph/auto-email

https://store.usbong.ph/index.php/auto-email

(2) Note for changes in column "Batches Sent". X/Y

=============

NOTES

=============
(1) Again, setting up the cron script will save you a lot of time compared
to adding a manual kick button and having to click the button each time you
have something to kick.

     But go with what you prefer.

(2) If something is in queue but no email is sent out after you kick the
script, please send me the kick script log file.

     It likely has to do with server time settings not set to PH time.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. Let me see if doing the following would cause auto-email to send an email.
`php index.php auto-email/autoemail run
`

As for the server time, it's set to HK time, which is the same with PH time.

I'll let you know if your suggestion worked.

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
I ran the following command on prod.
`php index.php auto-email/autoemail run`

However, I received an error message saying:

> Type: Error
> Message: Call to undefined function create_product_url()
> Filename: .../application/controllers/auto-email/Autoemail.php
> Line Number: 115
> 

Could it be that the code that I'm using, which is the same one  we have on our GitHub repo, is not updated?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Please check if this file is in your prod server. If it's not, please
include it: UsbongStore/usbong_store/application/helpers/MY_url_helper.php

Git Ref:
https://github.com/usbong/UsbongStore/blob/master/usbong_store/application/helpers/MY_url_helper.php

Email Ref: Usbong: Auto-email Component Reusable Functions

Note: This logic is placed outside auto-email folder cause it can be used
for old code as well.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. I have placed `MY_url_helper.php` in prod.

After running the following command, the status of the batch that I want to send in my auto-email queue became ACTIVE.

However, I did not receive an email from auto-email.

If the `Target Kick datetime stamp` has already passed, does that mean that auto-email will no longer send the email?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Please read on.

On Thu, Nov 9, 2017 at 5:14 PM, Masarap Mabuhay <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> OK. I have placed MY_url_helper.php in prod.
>
> After running the following command, the status of the batch that I want
> to send in my auto-email queue became ACTIVE.
>
Oks!

Please refresh your browser.

"ACTIVE"  is a temporary state.

It should go to "DONE" or "ERROR" shortly.

If it went to "ERROR", you should also see an error message.

> However, I did not receive an email from auto-email.
>
Did you activate logging? If yes, please send me log file so I can see what
happened.

Location:
UsbongStore/usbong_store/application/logs

Particularly, I'd like to identify who's email was targeted.

> If the Target Kick datetime stamp has already passed, does that mean that
> auto-email will no longer send the email?
>
No.

Email will only be sent if Target Kick Datetime has passed.

Additionally, the older the Target Kick Datetime, the higher priority is
given to that email to be sent out.

Good afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

1) I have refreshed the browser, but the state remains in "ACTIVE" state.

2) OK. I've activated logging by doing the following:
--> Made my `/application/logs` folder writable
--> In `/application/config/config.php`, I set `$config['log_threshold'] = 1;` 
--> Reference: [stackoverflow](https://stackoverflow.com/questions/3209807/how-to-do-error-logging-in-codeigniter-php); last accessed: 20171109
--> For some reason, though, I'm not getting any logs.
--> the target email is only: support@usbong.ph

3) OK. Target Kick Datetime should have already passed.

Thank you for the explanations.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

=============
REQUEST
=============

(1) Please send me a screen shot of your live server's auto email dashboard:
     store.usbong.ph/index.php/auto-email

(2) Please set log_threshold to 3 as specified in previous messages in this
thread and our auto-email wiki.

(3) Please export your live server's database and send them to me.

=============
TO DO
=============

(1) I'd like to check if your database has been corrupted because of the
unsafe error handling that occurred when db debug was not set correctly.

(2) I'd like to check if your database has been corrupted because of the
unsafe error handling that occurred when MY URL HELPER was not present in
your environment.

Good evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. I have emailed you the following:
1) Usbong Store SQL DB (prod)
2) Auto-email Dashboard Screenshot
3) Auto-email Logs (log_threshold = 3)

Please let me know if you need anything else.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Thank you for sending.

==========
PROBLEMS
==========

Your database is in a corrupted state.

This is seen in entry 12 of `auto_email_schedule` table.

This most likely happened because of the ff:
(a) Missing helper file from production environment*
(b) Misconfiguration of db_debug in production environment

*Most probable cause

==========
INFO
==========

I have also checked your log file and your dashboard.

The log entry "AUtoEmail: Nothing is in queue" is expected based on your
current settings.

All queues are currently paused in your live server (other than the corrupt
queue).

===========
REQUEST
===========

Please do the following steps.

*FIX CORRUPT DATABASE*

(1) Using your live server's PHP MY ADMIN, please open table
`auto_email_schedule`

(2) Look for entry 12 and set status FROM ACTIVE to QUEUED.

*CHECK IF CORRUPTION IS FIXED*

(1) Open your dashboard at the url below:

     store.usbong.ph/auto-email

(2) Look for Entry with the FF data:

     ID = 3

     Subject = Usbong.PH has New Recommendations for You

(3) Click "the menu icon" under column *Actions*:

(4) Check that "Status" is no longer "ACTIVE". It should read like 0/1.

*KICK AUTO EMAIL*

(1) Sign in to live server using ssh

(2) Kick the auto email script

*VALIDATE AUTO EMAIL KICK*

(1) Open support@usbong.ph and check if it received an email from
usbong.ph@gmail.com.

(2) Open log file and see what happened.

(3) Send log file to me for the next problem.

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Good news!

Your suggestions resolved the issue.
I was able to send an email using auto-email.

Thank you.

This case is now closed.

Peace,
Mike

**Comment by zent-lim** [comment]
Yehey! 😆😆😆

(1) Were the images correct when you opened the email?

I'd like to validate this field in your config file:
$config['base_url'] = 'http://localhost:8080/usbong_store/';

(2) If you're done debugging, you may set log_threshold back to your
original value.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

1) Yes, I have sent you a copy of the email that auto-email sent.
--> Here is the value of this field in prod's config file:
`$config['base_url'] = 'https://store.usbong.ph/';
`

2) OK.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Looks good! Yay! 😆😆😆
