### ISSUE TITLE
Auto-email: value of Target Kick Time is incorrect

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#28]
Hi Zent,
I was using auto-email now to send a recommendation to customers, and I noticed that the value of the Target Kick Time is incorrect.

It's saying: 
`2017-11-28 05-58:09`

But my current time is: 
`2017-11-28 13-58-00`

Despite this, I am able to send the auto-email.

In the core Usbong Store code, I use something like this:

```
date_default_timezone_set('Asia/Hong_Kong');			
$addedDateTimeStamp = date('Y-m-d H:i:s', $this->uri->segment(4));

```
Could adding `date_default_timezone_set('Asia/Hong_Kong');` be a solution?

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Yes. That's the most likely cause.

I will add the said line in config.php.

Good afternoon!

**Comment by zent-lim** [comment]
Hi Mike,

I added the line of code in config.php in commit 3ece483cc90bf302ee233ad316fc0d0f3f4b0e76.

I have also noted it in wiki page:
https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature

Afternoon!

**Comment by masarapmabuhay** [comment]
OK, Zent! Thanks!

Peace,
Mike
--
Usbong: Uplifting Human Lives
*www.usbong.ph <http://www.usbong.ph/>*
--
Michael B. Syson

**Comment by masarapmabuhay** [comment]
Hi Zent,
I was sending a new batch via auto-email, and for some reason, the admin dashboard is saying: 

> There is nothing that needs to be kicked right now.

The datetime stamp is: `2017-12-25 16:18:00` (correct)
My datetime stamp at the time: `2017-12-25 16:20:00`

After I modified the DB entry via phpmyadmin to `2017-12-25 01:18:00` (`01:18:00`, instead of `16:18:00`), the admin dashboard notified me that there was now something to kick.

Would you be able to offer suggestions on how to resolve this issue?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

On Dec 25, 2017 4:30 PM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
I was sending a new batch via auto-email, and for some reason, the admin
dashboard is saying:

There is nothing that needs to be kicked right now.

An entry will only appear if the target kick time has passed.

The datetime stamp is: 2017-12-25 16:18:00 (correct)
My datetime stamp at the time: 2017-12-25 16:20:00

The behavior is wrong.

Since the target kick time (2017-12-25 16:18:00) has passed (current time
is 2017-12-25 16:20:00), an entry should have been shown.

So far, there are two possibilities.

(1) When the data was fetched, the current time was not yet greater
than 2017-12-25
16:18:00.

   May I know your basis for the current time of 16:20:00 please?

   Is it your laptop clock (as opposed to your server os clock, mysql
clock, php clock)?

   If that is the case, the difference is acceptable.

   Then there is nothing to correct.

   Simply refresh the browser to make the entry appear.

(2) Your server clocks are not synced.

    Using whatever server was used, let's check two clocks: php, and mysql.

    (a) Your php clock uses Hongkong based on the code below:

        File: UsbongStore/usbong_store/application/config

        Code: date_default_timezone_set('Asia/Hong_Kong');

        Using the server that you used to create the scenario, kindly check
if the said line of code is present.

     (b) Log in to phpmyadmin and run this SQL query:

         Query: SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);

         Please check if it returns "08:00:00"

Have a good day ahead!

After I modified the DB entry via phpmyadmin to 2017-12-25 01:18:00 (
01:18:00, instead of 16:18:00), the admin dashboard notified me that there
was now something to kick.

Would you be able to offer suggestions on how to resolve this issue?

Thank you.

Peace,
Mike

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/28#issuecomment-353848370>,
or mute the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

1) Yes, your conjecture is correct. `16:20:00` was based on my laptop clock.
--> As a matter of fact, I did refresh the page using auto-email's refresh button, but to no avail.

2) a) True. The server clock is based on Hong Kong time.
b) After running the SQL query, it returned: `00:00:00`.
--> must I put: `08:00:00`?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Your server mysql clock doesn't seem to be in sync with your php timezone
clock.

Let me research a quick way to resolve it for your use case....

Ref:
https://stackoverflow.com/questions/930900/how-do-i-set-the-time-zone-of-mysql

Using phpmyadmin, please run the ff queries:

(1) SELECT @@global.time_zone;

      Copy the return value should you wish to revert back to the original
setting.

      For my case, it returns "SYSTEM"

(2) SET GLOBAL time_zone = '+8:00';

(3) Do some checks:

     (a) SELECT @@global.time_zone;

           This should return +08:00

     (b) SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);

      This should return "08:00:00"

   (c) Please check if the problem is resolved using your original use case.

(4) If the problem is not resolved, please set time_zone back to its
original value then let's analyze further.

Good morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, your solution resolved the issue.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Awesome! Have a good day ahead! 😊
