### ISSUE TITLE
Auto-email: Unsubscribe "Authentication Failed" error

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#34]
Hi Zent,
I encountered the following errors after unsubscribing to the email sent by auto-email.
1.
> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: Missing argument 1 for Administer::unsubscribe(), called in /var/www/html/system/core/CodeIgniter.php on line 481 and defined
> 
> Filename: auto-email/Administer.php
> 
> Line Number: 291
> 
> Backtrace:
> 
> File: /var/www/html/application/controllers/auto-email/Administer.php
> Line: 291
> Function: _error_handler
> 
> File: /var/www/html/index.php
> Line: 308
> Function: require_once

2)
> A PHP Error was encountered
> 
> Severity: Notice
> 
> Message: Undefined variable: encrypted_customer_id
> 
> Filename: auto-email/Administer.php
> 
> Line Number: 301
> 
> Backtrace:
> 
> File: /var/www/html/application/controllers/auto-email/Administer.php
> Line: 301
> Function: _error_handler
> 
> File: /var/www/html/index.php
> Line: 308
> Function: require_once

3)
> Authentication Failed
> 
> The data submitted for email unsubscribe has been tampered.

Please let me know if there's anything I can help you with.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Pls check if config file has field encryption_key set.

Here is a snip from release notes:

<----- snip ---->

    (c) Notes:
        (ii) I updated common file config/config.php and set field
encryption_key for unsubscribe feature.

<----- end ----->

Evening!

On Dec 8, 2017 5:07 PM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
I encountered the following errors after unsubscribing to the email sent by
auto-email.
1)

A PHP Error was encountered

Severity: Warning

Message: Missing argument 1 for Administer::unsubscribe(), called in
/var/www/html/system/core/CodeIgniter.php on line 481 and defined

Filename: auto-email/Administer.php

Line Number: 291

Backtrace:

File: /var/www/html/application/controllers/auto-email/Administer.php
Line: 291
Function: _error_handler

File: /var/www/html/index.php
Line: 308
Function: require_once


   1.

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: encrypted_customer_id

Filename: auto-email/Administer.php

Line Number: 301

Backtrace:

File: /var/www/html/application/controllers/auto-email/Administer.php
Line: 301
Function: _error_handler

File: /var/www/html/index.php
Line: 308
Function: require_once


   1.

Authentication Failed

The data submitted for email unsubscribe has been tampered.

Please let me know if there's anything I can help you with.

Thank you.

Peace,
Mike

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/34>, or mute the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I checked `config/config.php`.

It has the following: `$config['encryption_key'] = '';`

Please let me know if this is correct, or if I need to modify something.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Here is the proper setting:
$config['encryption_key'] = hex2bin('8fd7e0b96252a3f9d7bd37c57fbfed20');

Ref:
https://github.com/usbong/UsbongStore/blob/master/usbong_store/application/config/config.php

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have generated a new encryption key as you advised.
I have also put the key in the config file.

However, I am still encountering the same error message.

What could be the probable cause?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike!

Is the current problem the third problem?

"Data has been tampered with"

If yes, the same key must be ised to send out the email and catch the
unsubscribe link.

Not ok:
(1) send email using encryption key A
(2) change encryption key
(3) click unsubscribe link

Ok:
(1) set enncryption key
(2) send email
(3) click unsubscribe link

Request:
If this is not the error u ecountered, pls let me know which of the three
errors happenned. Tnx!



On Dec 11, 2017 9:49 AM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the reply.

I have generated a new encryption key as you advised.
I have also put the key in the config file.

However, I am still encountering the same error message.

What could be the probable cause?

Thank you.

Peace,
Mike

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/34#issuecomment-350602972>,
or mute the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

As it turned out, I had to resend a new email from auto-email.
Your advice resolved it.

> Ok:
> (1) set enncryption key
> (2) send email
> (3) click unsubscribe link
> 

This case is now closed.

Thank you.

Peace,
Mike
