### ISSUE TITLE
Auto-email: email_frame_single_template, Recommended Image Dimensions

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#49]
Hi Zent,
I am now able to use auto-email's new email_frame_single_template.
However, I noticed that the image I upload gets cropped.

I have verified this with: 
1) 960x720px (the default image file output dimensions from PPT)
2) 264x352px (Usbong Store product item dimensions)

May I ask what is the recommended image dimensions?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

The image should be resized to w = 600 and height = 390.

The size u mentioned is too small.

Pls check if the file below made it to the server being tested:
https://github.com/usbong/UsbongStore/blob/master/usbong_store/assets/css/auto-email/create_data.css

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. I have resized the width and height to be: 600x390px.

The image preview shows an uncropped image.

However, after sending the auto-email, when I checked my inbox, the image in the email is cropped.

In the meantime, yes, the file you mentioned made it to prod. https://github.com/usbong/UsbongStore/blob/master/usbong_store/assets/css/auto-email/create_data.css

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Copy. Thanks for checking.

Are you using live server?

The test case you mentioned (opening an email) will only work if you use
live server.

(1) admin module needs to upload image to live server

(2) gmail has to retrieve email from live server to show it to email owner
(gmail can t access dev server)

The test case will fail if live server is not used.

Thanks!

On Jan 13, 2018 9:09 AM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the reply.

OK. I have resized the width and height to be: 600x390px.

The image preview shows an uncropped image.

However, after sending the auto-email, when I checked my inbox, the image
in the email is cropped.

In the meantime, yes, the file you mentioned made it to prod.
https://github.com/usbong/UsbongStore/blob/master/
usbong_store/assets/css/auto-email/create_data.css

Thank you.

Peace,
Mike

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/49#issuecomment-357396943>,
or mute the thread

**Comment by zent-lim** [comment]
Hi Mike,

Also, there is no need to crop the image manually to 600 x 390.

The upload procedure should take care of that.

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

1) Yes, I am using prod, i.e. the live server.
2) OK. Perhaps, the upload procedure will only auto-crop an uploaded image if its ratio is the same as 600x390px.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Copy.

Kindly send the ff to zentlim@gmail.com.
(1) image you used
(2) forward copy of the email created

I ll investigate further by running the test case on my end early next week.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. I have emailed you the items you requested. 

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
OK. I created a new auto-email email
using the "email_frame_single_template",
but I renamed the image file name.

It worked!

Perhaps, auto-email 
doesn't overwrite
image files with
the same name?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I had a check item for this and it passed.

I'll rerun the scenario on monday:
(1) create email
(2) edit email and check if file is updated

Good afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I cleared my browser's cache as you suggested in your response to my email and it resolved the issue.

Let me now close this case.

Please never hesitate to reopen and/or comment if you'd want to add anything more.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Cool!

Thanks Mike! 😀
