### ISSUE TITLE
Auto-email: Is there a way to view the design layout of email_frame_simple_template.php without actually sending an email?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#5]
Hi @zent-lim,
May I ask if there is a way to view the design layout of `email_frame_simple_template.php` without actually sending an email?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

Currently, there is no way to view the template without sending an email.

We can schedule it for Phase 2 should you require this feature.

On the other hand, I've already set up SQL V3 so you can kick an email
readily.

=============
PREREQ
=============

(1) The instructions below assume that you're local environment already has
the installs needed for sending emails as explained in the wiki below:

https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature

(2) Your environment has a fresh install of Auto Email SQL V3.

Note: simply delete all auto_email_* tables and import the sql.

=============
INSTRUCTIONS
=============

(1) Go to web dir:

cd /xxx/UsbongStore/usbong_store

(2) Kick the command below:

php index.php auto-email/autoemail run

(3) Expect an email sent to the email of customer_id = 1.

(4) Update view file as you see fit.

(5) Update row 1 of table `auto_email_schedule` > `status` to "QUEUED".

This resets the status to unsent.

If you don't do this step, the script will conclude that there are no
further emails to send out because you've already sent it out in step (2)
above.

(6) Repeat steps (2) to (5) as needed.

Have a good evening ahead!
=============
MISC
=============

For more information, you can activate script debug lines as documented in
the wiki page.

Good evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! Let me go through your instructions then.

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
Good news! I was able to successfully send an email using auto-email!

The email doesn't display images correctly though.

I have created a ticket of the issue https://github.com/usbong/UsbongStore/issues/9.

Thank you!

Peace,
Mike
