### ISSUE TITLE
Product Management: How is the "External URL" supposed to function?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#57]
Hi Zent,
May I kindly ask how the `External URL` field is supposed to function?

I have placed a link in the `External URL` field upon adding a new product in the Books category, but there is no clear indication that the new product's page on the Usbong Store actually uses the `External URL`.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

external_url field has no impact on front end. It has impact on auto-email.

During requirements analysis phase, you said you wanted the ff:
(1) a feature that will allow auto-email to promote products not in usbong
store
(2) you wanted the usbong product schema to store information of external
products
    - you mentioned that based from your past experience, retail store
owners would prefer it if usbong encoded their products

These are reflected using two new database fields

*(1) external_url: if this is set for a product, auto-email will use this
field to create a link instead of the default link logic for usbong store*

*     - this allows you to promote products of external retailers using
auto-email*
(2) show: this allows you to store product data (from outside usbong store)
and not display it on usbong store front end

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! I have verified that the "External URL" does, in fact, function as it should, given that is part of auto-email.

Thank you.

This case is now closed.

Peace,
Mike
