### ISSUE TITLE
Auto-email: email_frame_simple_template, does not load the data of the existing auto-email

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#58]
Hi Zent,
I've observed that the `email_frame_simple_template` does not load the data of the existing auto-email.

Steps to replicate behavior:
I.
1) Click the `Edit Email` button of an existing auto-email.
2) Click the `Set Data` link.
3) The "Email Subject" and the "Welcome Message" are empty.

II.
1) Click the `Edit Email` button of an existing auto-email.
2) Click the `Pick Products` link.
3) The supposedly already existing picked products are empty.

This error may have resulted from an update you made related to auto-email loading data of an existing auto-email, even if the auto-email email is supposedly new.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I tried both scenarios but both cases returned data.

QUESTION

Did you by any chance changed the template being used under "Choose
Template"?

If, yes. Then it's by design that the fields are cleared.

It's because choosing a different template requires a different structure
of data.

Therefore, when a template is changed, the loaded data is already
considered dirty.

REQUEST

If the scenario above is not the test case, please check if you have the
latest version of the file below:
usbong_store/application/controllers/auto-email/Administer.php
<https://github.com/zent-lim/UsbongStore/commit/7d6fba8065dc85b4e75aeb3a5b720d4ddc31e15a#diff-674a8c1ed82372068a8b0159c7bc1b44>

(1) The url below shows the latest update:

https://github.com/zent-lim/UsbongStore/commit/7d6fba8065dc85b4e75aeb3a5b720d4ddc31e15a

(2) The url below shows the latest version of file:

https://github.com/zent-lim/UsbongStore/blob/master/usbong_store/application/controllers/auto-email/Administer.php

Please pay particular attention to lines 280 to 310.

Have a good evening ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. Yes, you are correct.

Choosing a different template deletes the data of the present template.

Would it be possible to provide the admin person a warning message or a hint that says that the present data will be deleted if he/she changes to a different template (https://github.com/usbong/UsbongStore/issues/59)?

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
I am now closing this correspondence given that Zent has already responded with an affirmation to my question (https://github.com/usbong/UsbongStore/issues/59#issuecomment-358502156).

Thank you.

Peace,
Mike
