### ISSUE TITLE
Product Management: Indicate that the image to be uploaded should be 264x352px

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#69]
Hi Zent,
In the Product Management feature of the Usbong Store, I understand that the image should be 264x352px to fit properly in the image viewer.

However, this information is not indicated in the page at all.

It would be helpful for new users of the Product Management component if we add this as an enhancement.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

No need to specify. It's what the crop box below is for:
![image](https://user-images.githubusercontent.com/8021327/36833494-85e52fa8-1d6a-11e8-8143-46f95ba262f1.png)

No matter what size image the user uploads, the cropbox gives a preview of what will be taken (which is 264 x 352 as specified by your requirement).

Good afternoon!

**Comment by zent-lim** [comment]
Hi Mike,

I think you misunderstood the feature. There is NO NEED to resize your image 264x352 before uploading.

The UI will take care of both cropping and compression.

Afternoon!

**Comment by zent-lim** [comment]
Hi Mike,

We specifically chose this kind of UI so the user will not be bothered to crop the images before uploading.

Afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

Yes, it appears that the feature indeed crops the image to 264x352px.

However, instead of cropping, it should more aptly be "scaling" down to 264x352px.

As the user, I prefer to upload images that I took from my mobile device's camera, without having to do any additional editing if possible.

The images I take are larger than 264x352px, although it is still in the 4:3 ratio.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

The ui also does scale down. It s what the zoom buttons are for.

Furthermore, u can also scale up, not just down.

You can upload images directly taken from ur phone to the ui because of
three things:
(1) the code i wrote can crop
(2) the code i wrote can scale down (and up)
(3) the code i wrote can compress

No editing is required.

If the images from ur phone are larger than 264 x 352, then all you need to
do is zoom out using the ui.

Good afternoon!


On Mar 1, 2018 4:25 PM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the replies.

Yes, it appears that the feature indeed crops the image to 264x352px.

However, instead of cropping, it should more aptly be "scaling" down to
264x352px.

As the user, I prefer to upload images that I took from my mobile device's
camera, without having to do any additional editing if possible.

The images I take are larger than 264x352px, although it is still in the
4:3 ratio.

Thank you.

Peace,
Mike

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/69#issuecomment-369513067>,
or mute the thread

**Comment by zent-lim** [comment]
Wait...

Let me check that last statement

**Comment by zent-lim** [comment]
Hi Mike,

I think I get what you're pointining it.

If the image has a scale larger than 264 x 352, you can't zoom out further
to see the whole image.

**Comment by zent-lim** [comment]
Hi Mike,

(1) Please check if this patch will fit your use case.

File: UsbongStore/usbong_store/application/views/manage/product_form.php

Original Line of Code:

minZoom: 'fill',

New Line of Code:

minZoom: 'fit',

(2) Expected behavior:

Now, even if you're image is bigger than 264x352, you should still be able to capture the entire image within the cropbox.

![testb](https://user-images.githubusercontent.com/8021327/36835443-3639c1a6-1d71-11e8-9730-ff3115323c28.png)

Please let me know if this works out.

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I am now verifying if your solution resolves the issue.

Without knowing our recommended width and height ratio, it is difficult to determine the image dimensions, such that the tool doesn't crop the image more than what is necessary.

Would you agree to add a helpful message or hint to guide the client/merchant to use an image in the 4:3 ratio (height:width), e.g. 400x300px?

Thank you.

Peace,
Mike
p.s. In my earlier reply, I mentioned 4:3 ratio, while referring to 264x352px. It should more aptly be 3:4, because 264px is the width, and the 352px is the height.

**Comment by zent-lim** [comment]
Hi Mike,

If the fix is implemented, the tool will no longer crop the image unnecessarily.

Did you get a chance to test the patch yet? Please let me know how it turns out.

If the patch works and you still feel the need for the hint, sure, we can add it.

Afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

May I ask if you included the patch in your pull request https://github.com/usbong/UsbongStore/issues/68?

If so, it seems that the tool is still unable to crop images with the incorrect width:height ratio, i.e. 3:4.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

No. The patch is not included pending ur test results.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I've already updated prod to use the newest commits, which include your pull requests.

I uploaded images using the Product Management interface, but the result remains the same.
The tool is unable to properly crop images.

The Zoom Out feature seems to be able to zoom out only to a certain extent.
For some reason, if the image's width and height is 300x300px, I can only zoom out to about 290x290px.

Please never hesitate
to tell me if you have
questions, or if there's
anything you'd want me
to clarify for you.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Did u use the patch i gave which is NOT included in the code update?

Thanks.


On Mar 7, 2018 8:26 AM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the reply.

I've already updated prod to use the newest commits, which include your
pull requests.

I uploaded images using the Product Management interface, but the result
remains the same.
The tool is unable to properly crop images.

The Zoom Out feature seems to be able to zoom out only to a certain extent.
For some reason, if the image's width and height is 300x300px, I can only
zoom out to about 290x290px.

Please never hesitate
to tell me if you have
questions, or if there's
anything you'd want me
to clarify for you.

Thank you.

Peace,
Mike

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/69#issuecomment-370978343>,
or mute the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I've updated the following file as you advised:
File: `UsbongStore/usbong_store/application/views/manage/product_form.php`

Original Line of Code:

`minZoom: 'fill',`

New Line of Code:

`minZoom: 'fit',`

It seems to have resolved the issue.

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Thanks Mike!

(1) I ll add this piece of code on my next update. (If i pull and see that
it s not yet included)

(2) Would u like the same thing reflected to auto email image upload?

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

1) OK. I have committed the code with the patch you advised to prod.
2) Yes, please.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi MIke,

I have sent a pull req at:
https://github.com/usbong/UsbongStore/pull/75

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Your fix resolved the issue.

In fact, the automated zooming appears better than my recommendation.

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
:)

On Mar 9, 2018 3:49 PM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the reply.

Your fix resolved the issue.

In fact, the automated zooming appears better than my recommendation.

This case is now closed.

Thank you.

Peace,
Mike

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/69#issuecomment-371738686>,
or mute the thread
