### ISSUE TITLE
Mobile Responsiveness: As Admin, dropdown menu is displayed behind the "Sell us back your books..." Ad

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#97]
Hi Zent,
I am performing Unit-Testing of your mobile responsiveness code update.

**Observation:**
When logged in as an Admin, the dropdown menu is displayed behind the "Sell us back your books..." Ad.

This behavior occurs both in Google Chrome and Firefox Quantum.

a) Google Chrome: Version 66.0.3359.139 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/344066/39974584-5a85693c-575c-11e8-8a5f-beaf7639799a.png)

b) Firefox Quantum: 59.0.3 (64-bit)

![image](https://user-images.githubusercontent.com/344066/39974591-64c5038a-575c-11e8-9bbf-d2f8afe2aac8.png)

Would you be able to resolve this issue?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Good Day Mike,

Thank you for reporting this problem.

(1) I was able to recreate the problem in the latest code:

![error](https://user-images.githubusercontent.com/8021327/39974858-d6df5618-575d-11e8-8f37-841c297458cd.png)

(2) I tested if the problem was present in my stable April 22 version (because I did test for this already):

      Command:  git checkout ba60676e7b057ce9a0303aef7f2d881e33d3888d

(3) I regret to inform that the problem is not present in my older more stable version.

![stablecode](https://user-images.githubusercontent.com/8021327/39974895-072299a2-575e-11e8-86e8-3f262896942f.png)

(4) This problem is again caused by unstable code not pushed by me.

(5) This is outside of the scope of my deliverables. I am reverting the ticket back to you.

Best of luck!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. I have resolved the issue: https://github.com/usbong/UsbongStore/commit/d191e89287f4ac1d3ecbe27b72e03e20e7407729

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

The update looks good! Morning!

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike
